### PR TITLE
Provide a getDateClass for easy overriding of date class type.

### PR DESCRIPTION
**Pull request by keithburgoyne**

### CODE REVIEW

**Comment by gauthierm** [comment]
Why is this needed?

**Comment by keithburgoyne** [comment]
Because code which uses RapAccounts assume dates are SwatDate objects. It broke the app api and possibly other code.

**Comment by gauthierm** [comment]
@keith I recommend we use https://github.com/silverorange/json-api-client/pull/25 instead.

**Comment by keith** [comment]
Wrong Keith 😄

**Pull request closed without merging**
